# Generated by Django 4.2.6 on 2024-03-12 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('time_to_start', models.DateTimeField()),
                ('min_count_of_members', models.SmallIntegerField()),
                ('max_count_of_members', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardqode.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hardqode.teacher'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hardqode.product')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hardqode.product')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardqode.student')),
            ],
        ),
    ]
