# Generated by Django 4.2.6 on 2024-03-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardqode', '0002_alter_group_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
