# Generated by Django 4.2.6 on 2024-03-12 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardqode', '0003_alter_teacher_first_name_alter_teacher_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_people',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Максимум человек в группе'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_people',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Минимум человек в группе'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Наименование группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hardqode.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardqode.student', verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.CharField(max_length=150, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hardqode.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hardqode.teacher', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_to_start',
            field=models.DateTimeField(verbose_name='Дата старта обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='available_products',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hardqode.product', verbose_name='Доступные продукты'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
