# Generated by Django 4.2.6 on 2024-03-12 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardqode', '0008_remove_group_students_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hardqode.product', verbose_name='Продукт'),
        ),
    ]
