# Generated by Django 4.2.6 on 2024-03-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardqode', '0010_alter_group_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, to='hardqode.student', verbose_name='Студенты'),
        ),
    ]
