# Generated by Django 4.2.6 on 2024-03-13 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardqode', '0011_alter_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_people',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Максимум человек в группе'),
        ),
    ]
