# Generated by Django 4.2.6 on 2024-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardqode', '0012_alter_product_max_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование группы'),
        ),
    ]
