# Generated by Django 4.2.6 on 2024-03-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardqode', '0014_alter_product_max_people_alter_product_min_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uniform_distribution',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
