# Generated by Django 4.2.6 on 2024-03-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardqode', '0015_product_uniform_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uniform_distribution',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
