# Generated by Django 4.2.6 on 2024-03-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardqode', '0016_alter_product_uniform_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hardqode.teacher', verbose_name='Автор'),
        ),
    ]
