# Generated by Django 4.2.6 on 2024-03-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardqode', '0017_alter_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='hardqode.product', verbose_name='Продукт'),
        ),
    ]
